source 'http://rubygems.org'

group :development do
    gem 'guard'
    gem 'guard-rspec'
    gem 'rb-inotify'
    gem 'rb-kqueue'
    gem 'rb-fsevent', :require => false
    gem 'rb-fchange', :require => false
    gem 'simplecov'
end
